- name: Checkout code
  uses: actions/checkout@v4

- name: Clean build directory
  run: |
    if (Test-Path build) {
      Remove-Item -Recurse -Force build
    }

- name: Build mod
  uses: geode-sdk/build-geode-mod@main
  with:
    sdk: latest
    build-config: RelWithDebInfo
